name: CI
on:
  push:

jobs:
  # linting & prettier
  linting:
    name: Linting & Prettier
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      HUSKY: 0
      HUSKY_SKIP_HOOKS: 1
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run lint
      - run: npm run pretty
  # tests
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      HUSKY: 0
      HUSKY_SKIP_HOOKS: 1
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm test
